### ISSUE TITLE
QHash/QMultiHash issue

### ISSUE THREAD

**Issue by Dariusz1989** [narnaud/qt6natvis#1]
Hey

I'm on Clion so maybe thats the issue but I have this with your test >

![image](https://user-images.githubusercontent.com/13185728/219602455-6a1c54e8-e4bd-4397-83bb-846b810e9a53.png)

**Comment by narnaud** [comment]
@Dariusz1989 Could you give another try, I tested with VS Code (using VS2019 and VS2022 as compiler) and Visual 2022, and both are working fine.
I did quite a lot of changes this week-end.

If it's not working, I may give a try with Clion, no promises.

**Comment by narnaud** [comment]
Unfortunately, that's a limitation of Clion, see blog here: https://blog.jetbrains.com/clion/2021/06/clion-2021-2-eap-natvis-support-freertos/#ImprovedNatvissupport
They don't support [CustomListItems](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019#customlistitems-expansion), which is used for `QHash`.

Unfortunately, I don't have any solution, there's no other way to provide a view for `QHash`. `QVariant`, which is not using `CustomListItems`, is working fine:
![image](https://user-images.githubusercontent.com/469305/220130220-41e6f66c-8670-4fc4-9582-b51bcc03e0e0.png)

You should ask JetBrains to integrate `CustomListItems`, or use Visual Studio or VS Code for debugging.
